from fastapi import FastAPI
import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest
import requests

app = FastAPI(title="AWS Weather Anomaly Detection API", version="1.2")

def fetch_aws_telemetry():
    # Coordinates for Raipur, Chhattisgarh, India
    url = "https://api.open-meteo.com/v1/forecast?latitude=21.2514&longitude=81.6296&hourly=temperature_2m,relative_humidity_2m,surface_pressure,wind_speed_10m,precipitation"
    response = requests.get(url).json()
    hourly = response.get("hourly", {})
    
    df = pd.DataFrame({
        "time": hourly.get("time", []),
        "temperature": hourly.get("temperature_2m", []),
        "humidity": hourly.get("relative_humidity_2m", []),
        "pressure": hourly.get("surface_pressure", []),
        "wind_speed": hourly.get("wind_speed_10m", []),
        "precipitation": hourly.get("precipitation", [])
    })
    return df.dropna()

@app.get("/api/analyze-station")
def analyze_station():
    df = fetch_aws_telemetry()
    
    # --- FEATURE ENGINEERING: Lags & Rolling Averages ---
    df["temp_lag1"] = df["temperature"].shift(1)
    df["temp_rolling_mean"] = df["temperature"].rolling(window=3).mean()
    df["pressure_rolling_mean"] = df["pressure"].rolling(window=3).mean()
    
    # Drop rows with NaN values generated by shifting/rolling
    df = df.dropna().reset_index(drop=True)
    
    # Multi-sensor feature matrix incorporating temporal context
    features = df[[
        "temperature", 
        "temp_lag1", 
        "temp_rolling_mean", 
        "pressure", 
        "pressure_rolling_mean", 
        "humidity", 
        "wind_speed", 
        "precipitation"
    ]]
    
    # Train Isolation Forest model using decision function thresholds
    model = IsolationForest(n_estimators=100, random_state=42)
    model.fit(features)
    
    # decision_function gives an anomaly score: lower values = more anomalous
    df["anomaly_score"] = model.decision_function(features)
    
    # Strict threshold: Anything below -0.15 is a genuine severe outlier/fault.
    # If weather is normal, 0 anomalies will be flagged.
    THRESHOLD = -0.15
    df["status"] = df["anomaly_score"].apply(lambda x: "Anomaly Detected" if x < THRESHOLD else "Normal")
    
    anomalies_df = df[df["status"] == "Anomaly Detected"]
    
    # --- CRITICAL FIX: RETURN STATEMENT ADDED HERE ---
    return {
        "status": "success",
        "station_id": "AWS-RAIPUR-CG-01",
        "location": "Raipur, Chhattisgarh",
        "total_readings_processed": len(df),
        "total_anomalies_flagged": len(anomalies_df),
        "recent_telemetry": df.tail(100).to_dict(orient="records"),
        "anomaly_logs": anomalies_df.to_dict(orient="records")
    }